version: "3.8"

services:

  redis:
    image: redis:alpine
    container_name: redis

  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    container_name: django_container_app
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Hitech_BIMS
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mahadev123
    container_name: postgres_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      start_period: 5s

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker --loglevel=DEBUG
    volumes:
      - .:/django
    container_name: celery
    depends_on:
      - redis
      - app
      - db


    # image: mysql:5.7
    # environment:
    #   MYSQL_DATABASE:'djnago-app-db'
    #   MYSQL_ALLOW_EMPTY_PASSWORD:'true'
    # volumes:
    #   - ./data/mysql/dbb:var/lib/mysql
    

  


# services:
#   app:
#     build: .
#     volumes:
#       - .:/django
#     ports:
#       - "8000:8000"
#     container_name: django_container_db
#     command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     volumes:
#       - ./data/db:/var/lib/postgres/data
#     environment:
#       - POSTGRES_DB="docker_db"
#       - POSTGRES_USER="postgres"
#       - POSTGRES_PASSWORD="Chetu@123"
#     container_name: postgres_db
    
